export default {
  REQUEST_GEOCODE: "REQUEST_GEOCODE",
  REQUEST_GEOCODE_SUCCESS: "REQUEST_GEOCODE_SUCCESS",
  REQUEST_GEOCODE_FAILED: "REQUEST_GEOCODE_FAILED",

  SET_ORIGIN_DESTINATION: "SET_ORIGIN_DESTINATION",
  SET_ROUTES: "SET_ROUTES",
  SET_ROUTE: "SET_ROUTE",
  SET_ROUTES_SORT: "SET_ROUTES_SORT",
};
